#!/usr/bin/env python3
"""Wrap a Windows `linkr.exe` into a self-extracting PowerShell terminal.

Usage:
    python3 tools/build_terminal_bundle.py --exe path/to/linkr.exe \\
        [--output dist/linkr-bee-terminal.ps1] [--name linkr.exe] \\
        [--version 1.0.0]

The generated script embeds the executable as base64, unpacks it once into
`%LOCALAPPDATA%\\LinkrBee\\bin`, verifies the embedded SHA-256 before running it,
and then starts it with the arguments the script itself was called with,
forwarding the exit code. Nothing else is unpacked: the payload is a single
console executable, so the deliverable stays a plain `.ps1` that
`powershell -File` or a double click can run.

Build the payload first with `tools/build_terminal.ps1 -Bundle`, or build
`linkr.exe` anywhere and point this generator at it. The tests in
`tests/test_terminal_bundle.py` cover the generator.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
CARGO_TOML = ROOT / "tools" / "linkr-cli" / "Cargo.toml"
DEFAULT_OUTPUT = ROOT / "dist" / "linkr-bee-terminal.ps1"

# Marks around the base64 block; the tests and a curious reader use them to
# pull the payload back out of the script.
PAYLOAD_BEGIN = "# linkr-bee payload begin"
PAYLOAD_END = "# linkr-bee payload end"
B64_LINE = 120

# Both land in the generated PowerShell source, so keep them to characters
# that need no escaping inside the here-string or the single quotes.
SAFE_NAME = re.compile(r"[A-Za-z0-9._-]+\.[A-Za-z0-9]+")
SAFE_VERSION = re.compile(r"[A-Za-z0-9.+-]+")


def cargo_version() -> str:
    """Version of the terminal crate, read from Cargo.toml without running cargo."""
    match = re.search(r'^version\s*=\s*"([^"]+)"', CARGO_TOML.read_text("utf-8"), re.M)
    return match.group(1) if match else "unknown"


def payload_block(payload: bytes) -> str:
    """The base64 payload, cut into short lines so the script stays greppable."""
    encoded = base64.b64encode(payload).decode("ascii")
    lines = [encoded[index:index + B64_LINE] for index in range(0, len(encoded), B64_LINE)]
    return "\n".join(lines)


def build_script(payload: bytes, *, name: str, version: str, source: str = "") -> str:
    """Render the self-extracting script for one executable."""
    if not payload:
        raise ValueError("refusing to bundle an empty executable")
    if not SAFE_NAME.fullmatch(name):
        raise ValueError(f"unsafe payload name: {name!r}")
    if not SAFE_VERSION.fullmatch(version):
        raise ValueError(f"unsafe version: {version!r}")

    digest = hashlib.sha256(payload).hexdigest()
    origin = f"{source}, " if source else ""
    header = f"""\
# linkr-bee-terminal.ps1 — self-extracting Linkr Bee terminal
#
# Generated by tools/build_terminal_bundle.py from {origin}{version},
# {len(payload)} bytes. Rebuild it instead of editing it by hand.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\\linkr-bee-terminal.ps1 --help
#   .\\linkr-bee-terminal.ps1 --name 'Linkr BLE UART' --scan
#   .\\linkr-bee-terminal.ps1 --tui
#
# The executable is unpacked once into %LOCALAPPDATA%\\LinkrBee\\bin and reused
# afterwards; delete that folder to force a fresh unpack. The terminal's exit
# code is forwarded, so `if ($LASTEXITCODE)` works as usual.
"""

    body = f"""\
{header}
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $false

$payloadName = '{name}'
$payloadVersion = '{version}'
$payloadSha256 = '{digest}'

$binDir = if ($env:LOCALAPPDATA) {{
    Join-Path $env:LOCALAPPDATA 'LinkrBee\\bin'
}} else {{
    Join-Path ([IO.Path]::GetTempPath()) 'LinkrBee\\bin'
}}
$exePath = Join-Path $binDir $payloadName

{PAYLOAD_BEGIN} — base64 of {name}, {len(payload)} bytes
$payload = @'
{payload_block(payload)}
'@
{PAYLOAD_END}

function Get-PayloadSha256([string]$path) {{
    (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()
}}

# Re-unpack only when the file is missing or belongs to another bundle: the
# hash covers the embedded bytes, not the timestamp.
$fresh = $false
if (Test-Path -LiteralPath $exePath) {{
    $fresh = (Get-PayloadSha256 $exePath) -eq $payloadSha256
}}
if (-not $fresh) {{
    New-Item -ItemType Directory -Force -Path $binDir | Out-Null
    $bytes = [Convert]::FromBase64String(($payload -replace '\\s', ''))
    $algorithm = [Security.Cryptography.SHA256]::Create()
    try {{
        $actual = [BitConverter]::ToString($algorithm.ComputeHash($bytes)).Replace('-', '').ToLowerInvariant()
    }} finally {{
        $algorithm.Dispose()
    }}
    if ($actual -ne $payloadSha256) {{
        throw "linkr-bee: embedded payload checksum mismatch; rebuild the bundle"
    }}
    [IO.File]::WriteAllBytes($exePath, $bytes)
}}

# Quote only the arguments that need it, then hand them to the terminal
# verbatim: no wrapper process, so Ctrl+C and the exit code stay honest.
$arguments = foreach ($argument in $args) {{
    if ($argument -match '[\\s"]') {{ '"' + ("$argument" -replace '"', '""') + '"' }} else {{ "$argument" }}
}}

if ($arguments) {{
    $process = Start-Process -FilePath $exePath -ArgumentList $arguments -Wait -PassThru -NoNewWindow
}} else {{
    $process = Start-Process -FilePath $exePath -Wait -PassThru -NoNewWindow
}}
exit $process.ExitCode
"""
    return body


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the self-extracting Windows terminal script.",
    )
    parser.add_argument("--exe", required=True, type=Path, help="path to the Windows linkr.exe")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"script to write (default: {DEFAULT_OUTPUT.relative_to(ROOT)})",
    )
    parser.add_argument(
        "--name",
        default="linkr.exe",
        help="file name the payload is unpacked to (default: linkr.exe)",
    )
    parser.add_argument(
        "--version",
        default=None,
        help="version stamped into the script (default: the Cargo.toml version)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="print the script instead of writing the file",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not args.exe.is_file():
        print(f"build_terminal_bundle: no such executable: {args.exe}", file=sys.stderr)
        return 1
    payload = args.exe.read_bytes()
    version = args.version or cargo_version()
    try:
        script = build_script(
            payload,
            name=args.name,
            version=version,
            source=args.exe.name,
        )
    except ValueError as error:
        print(f"build_terminal_bundle: {error}", file=sys.stderr)
        return 2

    if args.stdout:
        sys.stdout.write(script)
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # CRLF by hand: `Path.write_text(newline=…)` needs Python 3.10, and the
    # script is generated from whatever interpreter is around.
    with args.output.open("w", encoding="utf-8", newline="\r\n") as handle:
        handle.write(script)
    print(
        f"Bundle: {args.output} ({len(payload)} bytes of {args.name}, version {version})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
