#!/usr/bin/env sh
# Assemble the GitHub Pages variant of the plain web terminal.
#
# web/ is the browser default and keeps the LAN bridge: a locally served page
# may open ws://, which is how the LAN bridge connects. An https origin such as
# GitHub Pages cannot, so the Pages variant copies web/ and overwrites the one
# module that switches the LAN bridge off. Nothing else differs, and that is
# what keeps the copy reviewable: the only file that is not a byte-for-byte
# copy of web/ is build_flags.js.
#
# Usage: tools/build_pages.sh [output-directory]   (default: build-pages)
set -eu

repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
out="${1:-$repo_dir/build-pages}"

rm -rf "$out"
mkdir -p "$out"
cp -R "$repo_dir/web/." "$out/"

cat > "$out/build_flags.js" <<'FLAGS'
/* Generated by tools/build_pages.sh for the GitHub Pages variant. An https
 * page cannot open ws://, so the LAN bridge is switched off and hidden. Serve
 * web/ locally with tools/serve_web.sh to use it. */
export const buildFlags = { lanBridge: false };
FLAGS
touch "$out/.nojekyll"

# Fail the build rather than publish a variant whose switch stopped matching
# what app.js reads: an unnoticed rename would publish the LAN entry to a place
# where it can only fail.
grep -q "lanBridge: false" "$out/build_flags.js"
grep -q "buildFlags.lanBridge" "$out/app.js"
